[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
new_dex = "C6yGxJWKa1d3GyD4Wz4Bi9MXtqPVhme5N1N8Cr6RU4mY"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 8000
